(cl:defpackage cares_msgs-msg
  (:use )
  (:export
   "<ARUCOMARKERS>"
   "ARUCOMARKERS"
   "<INSTANCEMASKS>"
   "INSTANCEMASKS"
   "<PLATFORMGOALACTION>"
   "PLATFORMGOALACTION"
   "<PLATFORMGOALACTIONFEEDBACK>"
   "PLATFORMGOALACTIONFEEDBACK"
   "<PLATFORMGOALACTIONGOAL>"
   "PLATFORMGOALACTIONGOAL"
   "<PLATFORMGOALACTIONRESULT>"
   "PLATFORMGOALACTIONRESULT"
   "<PLATFORMGOALFEEDBACK>"
   "PLATFORMGOALFEEDBACK"
   "<PLATFORMGOALGOAL>"
   "PLATFORMGOALGOAL"
   "<PLATFORMGOALRESULT>"
   "PLATFORMGOALRESULT"
   "<STEREOCAMERAINFO>"
   "STEREOCAMERAINFO"
  ))

