(cl:defpackage cares_msgs-srv
  (:use )
  (:export
   "ARUCODETECT"
   "<ARUCODETECT-REQUEST>"
   "ARUCODETECT-REQUEST"
   "<ARUCODETECT-RESPONSE>"
   "ARUCODETECT-RESPONSE"
   "CALIBRATIONSERVICE"
   "<CALIBRATIONSERVICE-REQUEST>"
   "CALIBRATIONSERVICE-REQUEST"
   "<CALIBRATIONSERVICE-RESPONSE>"
   "CALIBRATIONSERVICE-RESPONSE"
   "DETECTION"
   "<DETECTION-REQUEST>"
   "DETECTION-REQUEST"
   "<DETECTION-RESPONSE>"
   "DETECTION-RESPONSE"
  ))

